### ISSUE TITLE
Problem with location of Malawi Election Information Centre (Limbe, Malawi)

### ISSUE THREAD

**Issue by aa3181** [GovReady/odesurvey#214]
Used the look up to find lat-long info and enter it into admin tool - see error message below and look up screenshots

![screen shot 2015-07-22 at 9 35 03 am](https://cloud.githubusercontent.com/assets/11556988/8826509/faac04ca-3054-11e5-8acc-c7f1b846c01d.png)

![screen shot 2015-07-22 at 9 37 45 am](https://cloud.githubusercontent.com/assets/11556988/8826563/5890ef38-3055-11e5-956b-32a3cb6c8ef6.png)

**Comment by gregelin** [comment]
Corrected. Location Lat/Lon updates via admin interface now works.
