### ISSUE TITLE
Apparently incorrect data for data_use_type

### ISSUE THREAD

**Issue by gregelin** [GovReady/odesurvey#227]
Audrey reports that incorrect data use types are showing up in the published data.
Related to #229, #195

**Comment by gregelin** [comment]
From @aa3181:
- Mona School of Business & Management: change 'Demographics and statistics' to 'Demographics and social' in data use
- Bill & Melinda Gates Foundation: change 'Health' to Health/healthcare in data use 
- DhilCare: change 'Health/healhcare' to 'Health/healthcare' in data use
- Think Brite Solutions: change 'Publilc safety' to 'Public safety' in data use
- Innovation Accelerator: change 'Scientific research' to 'Science and research' in data use
- Transparent Chennai: change 'Transporation' to 'Transportation' in data use

**Comment by gregelin** [comment]
@aa3181 

Analysis of previous imported data indicates that the field `data_use_type` was not being consistently imported from the inventory spreadsheet into parse.com or AGOL. The "correction" in late May appears to stem from leaving out the importation of `data_use_type` all together rather than actual correction.

When importing started last week using the api call to http://www.opendataenterprise.org/map/survey/data/flatfile.json as the source, the field `use_data_type` started being imported, and introducing the above errors.

The admin screen currently does not allow editing for the field `data_use_type` because the data is stored as an array instead of a string. Additional programming needs to be done to enable editing through the admin interface.  (The field cannot currently be edited via the Parse web interface either."

**Comment by aa3181** [comment]
ok, can you fix the upload/data to reflect te edits made two months ago?

**Comment by gregelin** [comment]
ata_use_type field is a stored list of ALL types of data an organization uses. 
That list — data_use_type — is then used to generate the “data use” triples (e.g, data_type + data_src_country_name + data_src_gov_level)
We have only been publishing the “data use” information from the three fields — and that is the data that was cleaned up.
The data_use_type is a listing of just the selected data types in the survey, without any country or level of government affiliated. 
It is necessary to capture the generated list to create the data use triples. I stored that original list to have a record of that information.
The list of data types — as a list — was never published on the map, only the generated triples. 
We cleaned up the generated triples. We cleaned up the data_type field that was being published.
(and data_type is still being published).
Only what happened this week is we started also publishing ‘data_use_type’, too, in the updated schema.
We never cleaned up (or published) data_use_type before, only the data_type.
The map viz picked up the data_use_type field as well as the data_type field. That introduced the typographical errors into the map. And to you it looked like corrected data became incorrect b/c the misspelled values re-appeared.
But in fact, the corrected data is still corrected.
Probably the best solution is to drop the data_use_type field from the import. I will look at that. I am not sure if I can do it without BR also making a change.

**Comment by gregelin** [comment]
Extensive research in copies of arcgis_flatfile.json from various dates shows only `arcgis_flatfile.0528.json` having the corrected values.  Immediately proceeding file `arcgis_flatfile.706.0528.json` does not have corrected values.

The 05/28 corresponds to the date of Audrey's email with the list of corrections at 12:51 PM. 

However, data was imported from the inventory into parse database on 5/28 prior to Audrey's request for the changes at approximately 09:58 AM. And there does not appear to have been a subsequent import from inventory into the parse database.

The 05/28 data import was the final data corrections and import just before the initial presentation. So while the import into AGOL was successful, It appears I did not also upload that most recent version into the Parse.com arcgis_flatfile, leaving the arcgis_flatfile in parse.com out of sync for those few records.

Consequently, the data in parse.com database did not have the corrected values for `data_type` field, but the previous values. When we started importing the data from parse.com via the API into AGOL, the old data_type values were included for those records.

## Fix in arcgis_flatfile `data_type` field ##
- [x] Mona School of Business & Management: change 'Demographics and statistics' to 'Demographics and social' in data use
- [ ] Bill & Melinda Gates Foundation: change 'Health' to Health/healthcare in data use 
- [ ] DhilCare: change 'Health/healhcare' to 'Health/healthcare' in data use
- [ ] Think Brite Solutions: change 'Publilc safety' to 'Public safety' in data use
- [ ] Innovation Accelerator: change 'Scientific research' to 'Science and research' in data use
- [ ] Transparent Chennai: change 'Transporation' to 'Transportation' in data use

## Fixed in arcgis_flatfile `data_use_type` and `data_use_unparsed` field ##
- [ ] Mona School of Business & Management: change 'Demographics and statistics' to 'Demographics and social' in data use
- [ ] Bill & Melinda Gates Foundation: change 'Health' to Health/healthcare in data use 
- [ ] DhilCare: change 'Health/healhcare' to 'Health/healthcare' in data use
- [ ] Think Brite Solutions: change 'Publilc safety' to 'Public safety' in data use
- [ ] Innovation Accelerator: change 'Scientific research' to 'Science and research' in data use
- [ ] Transparent Chennai: change 'Transporation' to 'Transportation' in data use

**Comment by gregelin** [comment]
Data fixed and uploaded.
