### ISSUE TITLE
organization not appearing in admin tool - "itopia"

### ISSUE THREAD

**Issue by aa3181** [GovReady/odesurvey#240]
itopia has been added twice via the min required survey. neither entry is displayed in the admin tool. both are displayed in parse with profile ids T1TOfOfaSF and TTKoAarOW6

**Comment by gregelin** [comment]
This appears straight forward to correct. When we had a smaller data set, it was sufficient to make a single call to Parse.com to extract all the data. Now that the data set has crossed 1,000 records, we need to pull more data from Parse.

**Comment by aa3181** [comment]
Got it, thanks.

On 19 August 2015 at 09:23, Greg Elin <notifications@github.com> wrote:

> Closed #240 <https://github.com/GovReady/odesurvey/issues/240> via 92a8a0c
> <https://github.com/GovReady/odesurvey/commit/92a8a0c9240046cbf230336a6f8c1eacbcb22a87>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GovReady/odesurvey/issues/240#event-386487921>.
>



-- 
Audrey Ariss
Center for Open Data Enterprise <http://www.opendataenterprise.org> |
@odenterprise <http://twitter.com/odenterprise>
m: 917-680-2416
